import express from "express";
import ReceiptRouter from "./ReceiptRouter.js";
import MatchRouter from "./MatchRouter.js";
import LoginRouter from "./AuthRouter.js";
import CompanyRouter from "./CompanyRouter.js";
import YearRouter from "./YearRouter.js";
import CompanyInfoRouter from "./SettingRoutes/SetcompanyinfoRouter.js";
import SetDocumentNoRouter from "./SettingRoutes/SetdocumentnoRouter.js";
import SetBranchInfoRouter from "./SettingRoutes/SetBranchInfoRouter.js";
import SetPostingAccountRouter from "./SettingRoutes/SetPostingAccountRouter.js";
import SetChartOfAccountRouter from "./SettingRoutes/SetChartOfAccountRouter.js";
import SetDefaultBranchRouter from "./SettingRoutes/SetDefaultBranchRouter.js";
import SetActivePeriodRouter from "./SettingRoutes/SetActivePeriodRouter.js";
import customerRouter from "./CustomerRoute.js";
import menuRoutes from "./MenuRoute.js";
import ItemPageRouter from "./Purchase/Setup/ItemPageRouter.js";
import ItemGroupPageRouter from "./Purchase/Setup/ItemGroupPageRouter.js";
import UnitPageRouter from "./Purchase/Setup/UnitPageRouter.js";
import StaffPageRouter from "./Purchase/Setup/StaffPageRouter.js";
import UserLoginRouter from "./SecurityRoutes/UserLoginRouter.js";
import userpermission from "./SecurityRoutes/UserPermissionMenuRouter.js";
import userpermissionBranch from "./SecurityRoutes/UserPermissionBranchRouter.js";
import purchaseInvoiceRouter from "./Purchase/Transaction/PurchaseInvoiceRouter.js";
import branchRouter from "./common/BranchRouter.js";

const router = express.Router();

router.use("/Receipt", ReceiptRouter);
router.use("/Match", MatchRouter);
router.use("/auth", LoginRouter);
router.use("/companies", CompanyRouter);
router.use("/years", YearRouter);
router.use("/CompanyInfo", CompanyInfoRouter);
router.use("/DocumentNo", SetDocumentNoRouter);
router.use("/BranchInfo", SetBranchInfoRouter);
router.use("/PostingAccount", SetPostingAccountRouter);
router.use("/SetChartOfAccount", SetChartOfAccountRouter);
router.use("/DefaultBranch", SetDefaultBranchRouter);
router.use("/ActivePeriod", SetActivePeriodRouter);
router.use("/menu", menuRoutes);
router.use("/Item", ItemPageRouter);
router.use("/ItemGroup", ItemGroupPageRouter);
router.use("/Unit", UnitPageRouter);
router.use("/Staff", StaffPageRouter);
router.use("/customer", customerRouter);
router.use("/UserLogin", UserLoginRouter);
router.use("/user-permission", userpermission);
router.use("/user-permission-branch", userpermissionBranch);
router.use("/purchase-invoice", purchaseInvoiceRouter);
router.use("/branch", branchRouter);

export default router;
